### ISSUE TITLE
Installing fail

### ISSUE THREAD

**Issue by zjoin** [kitze/custom-react-scripts#13] opened 2016-10-03 12:49 UTC
I installing create-react-app my-app --scripts-version custom-react-scripts, but it's fail

![screen shot 2016-10-03 at 15 47 35](https://cloud.githubusercontent.com/assets/4652760/19037779/c217f188-8980-11e6-8d7a-0e2f35bb60c0.png)

How to fix it?

**Comment by andrewhl** [comment] 2016-10-03 13:04
I just came here to post the same issue. +1

**Comment by andrewhl** [comment] 2016-10-03 13:07
Running:

```bash
`npm install --save-dev --save-exact custom-react-scripts` failed
```

inside the project folder gives me:

```bash
npm ERR! Darwin 15.5.0
npm ERR! argv "/Users/andrew/.nvm/versions/node/v6.6.0/bin/node" "/Users/andrew/.nvm/versions/node/v6.6.0/bin/npm" "install" "--save-dev" "--save-exact" "custom-react-scripts"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3

npm ERR! Path must be a string. Received undefined
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/andrew/code/ideas/npm-debug.log
```

**Comment by jbach** [comment] 2016-10-03 13:12
@kitze [suggested](https://github.com/kitze/create-react-app/issues/10#issuecomment-251093990) downgrading to Node 6.2.0, which ought to fix the problem. I think it might also be a problem with npm 3.10.3 (introduced with node 6.3.0) rather than node itself, as using npm@3.8.3 on Node 6.7.0 works for me.

It also seems like this is only an issue with `custom-react-scripts` and not with the regular `react-scripts`? @kitze, maybe merging recent changes from facebookincubator/create-react-app to your fork would fix things?

**Comment by schabluk** [comment] 2016-10-03 14:45
Same here. Node v6.7.0, npm 3.10.8.

**Comment by claylevering** [comment] 2016-10-04 19:00
+1 to this and not really interested in downgrading my Node / NPM (or using alternatives with nvm).

**Comment by kitze** [comment] 2016-10-06 10:53
@jbach I just merged all the changes from the original create-react-app repo. I also merged few PRs and released version 0.0.15 on npm. I'm still getting the error. I'm investigating what can be the issue...

**Comment by andrewhl** [comment] 2016-10-07 16:06
Godspeed, my friend. I really want to use this library, but this failure is preventing me from even getting off the ground.

**Comment by spion** [comment] 2016-10-08 14:23
Sounds like an issue with bundledDependencies being "fixed" (but not fully) in latest npm: https://github.com/npm/npm/blob/b38573fae383aaaeaec0548c2ae616778a3b5dab/CHANGELOG.md#erk

Specifically it has problems when trying to normalize the path of `babel-preset-es2015` which is a bundled dependency included by `babel-preset-react-app`.

My guess is, if you remove stage-0 from the bundled dependencies list, it will work.

**Comment by kitze** [comment] 2016-10-08 16:58
@spion thank you! I'll test it and push a fix asap.

**Comment by kitze** [comment] 2016-10-08 17:02
@spion the problem is that bundledDependencies get generated from the release.sh script:

```
# This modifies $clean_path/package.json to copy all dependencies to bundledDependencies
node ./node_modules/.bin/bundle-deps
```

**Comment by raygesualdo** [comment] 2016-10-08 19:12
Just tried to give custom-react-scripts a shot today and ran into this install issue. Any quick fixes or hacks to get it working?

**Comment by claylevering** [comment] 2016-10-08 19:17
@raygesualdo I'v gotten around it by temporarily using npm@3.9.5 - `npm i -g npm@3.9.5`

**Comment by raygesualdo** [comment] 2016-10-08 19:26
Thanks @claylevering. Installed with npm@3.9.5 then reverted back to current npm version.

**Comment by spion** [comment] 2016-10-08 22:47
@kitze maybe something like this would work in `publish.sh`?

```js
node -e 'j=require("./package.json");j.bundledDependencies.splice(j.bundledDependencies.indexOf("babel-preset-stage-0"), 1);fs.writeFileSync("package.json",JSON.stringify(j,null,2))'
```

**Comment by schovi** [comment] 2016-10-14 12:47
Same here 
node 6.8.0
npm 3.10.8

**Comment by kitze** [comment] 2016-11-05 10:29
I removed the bundling of deps, because Facebook [is also planning to remove them too](https://github.com/facebookincubator/create-react-app/issues/986).

Installing should work fine now. Tested with latest node and npm.

**Comment by seanrasmussen** [comment] 2016-11-05 14:58
I still get an error -- probably too soon to close this...

**Comment by claylevering** [comment] 2016-11-05 15:58
@kitze - Not sure why, but `npm i custom-react-scripts` seems to still be trying to install an older version?

@seanrasmussen - Try this: `npm i --save-dev custom-react-scripts@0.0.17` - this will install at @kitze's latest version and I just verified that it will install in the following environments:

node:  `v7.0.0`
npm: `v3.10.9`

-C

**Comment by kitze** [comment] 2016-11-05 17:41
@seanrasmussen can you tell me which combination of node/npm do you have?

@claylevering I have no idea why it would install a different version when on npm it clearly says "0.0.17 is the latest of 16 releases" :|

**Comment by seanrasmussen** [comment] 2016-11-05 17:57
@kitze Node: 6.7.0   /   npm: 3.10.8

**Comment by seanrasmussen** [comment] 2016-11-05 18:16
BTW -- I just updated to node v7.0.0 and npm 3.10.9 and got the same error....

**Comment by kitze** [comment] 2016-11-21 15:26
Bundled dependencies are now removed. @seanrasmussen I just tested the app with both node/npm combinations that were failing for you. It worked fine: generating, running, building, ejecting.

Can you please try it again and let me know if it fails. Also @claylevering 🙏

**Comment by seanrasmussen** [comment] 2016-11-22 14:55
@kitze -- not sure why but I'm still not getting a successful install happening (sorry! :-))

**Comment by kitze** [comment] 2016-11-22 14:56
@seanrasmussen can you provide a log or something? Are you sure you're running ```create-react-app new-app --scripts version custom-react-scripts``` ?

**Comment by seanrasmussen** [comment] 2016-11-22 14:58
Yup -- I just pasted the command from the instructions into the command line and ran it... It issues a throw error... I'm heading out for a meeting now, but I'll re-run and send more info on errors...

**Comment by seanrasmussen** [comment] 2016-11-22 18:56
@kitze Here's a snap of my console after the error....
![capture](https://cloud.githubusercontent.com/assets/11204073/20537489/5e4da910-b0bb-11e6-983d-19cf29e1513b.JPG)

**Comment by kitze** [comment] 2016-11-23 07:38
Ah okay so this is a completely different error that you're getting. Maybe it's some issue with Windows. Which version are you using?

Also, does the default ```create-react-app app``` command work?

**Comment by seanrasmussen** [comment] 2016-11-23 12:39
@kitze  I'm using Windows 7 (64 bit).  I use create-react-app all the time without problems...

**Comment by kitze** [comment] 2016-12-12 12:20
@seanrasmussen I'm not sure if I should leave this issue open. Any updates with the latest version?

**Comment by kitze** [comment] 2016-12-12 13:19
@seanrasmussen I'm not sure if I should leave this issue open. Any updates with the latest version?

**Comment by seanrasmussen** [comment] 2016-12-12 13:44
@kitze -- I just ran it again and get the same error. Other Win7 users may have the same prob, but if you want to close it go for it. I'll just continue 'ejecting' from the create-react-app to add decorators support..

**Closed** 2017-03-15 21:01 UTC
